### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by Noovak** [clwie/sapphire#3]
When I compile it fails everytime. 
https://prnt.sc/1zbcgtq
What do I do to fix this?

**Comment by Spookycpp** [comment]
i fixed it under 2 minutes, its easy if you pay attention

**Comment by Noovak** [comment]
> i fixed it under 2 minutes, its easy if you pay attention

can you post it fixed then?

**Comment by clwie** [comment]
pushed fix for this

**Comment by EXC3L-YT** [comment]
what did you do to fix i have the same issue ?
